general:
  s3_bucket: victor-org-artifacts-ap-southeast-2 
  # auth:
  #   default: mf-demo-hub
  #   ap-southeast-2: mf-demo-hub
project:
  name: victor-wong-versent  
  regions:
    - ap-southeast-2
tests:
  apac-regions:  
    template: templates/workload.template.yaml
